[package]
name = "iceeburr/roblox-video-codec"
description = "STILL IN DEVELOPMENT, NOT READY FOR USE! Efficient encoding/decoding, and display of video files within Roblox. Seamless integration for any game."
version = "0.0.0"
authors = ["iceeburr"]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "sourcemap.json",
    "globalTypes.d.lua",
    "Packages",
    "app",
    "assets/videos",
]

[dependencies]
base64 = "reselim/base64@3.0.0"
