name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  autodeploy:
    runs-on: windows-latest
    env:
      ASSET_ID: ${{ vars.ASSET_ID }}
      PLACE_ID: ${{ vars.PLACE_ID }}
      GAME_ID: ${{ vars.GAME_ID }}
      DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
      WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wally Packages
        run: wally install

      - name: Generate Sourcemap
        run: rojo sourcemap test.project.json -o sourcemap.json

      - name: Export Wally Package Types
        run: |
          mkdir Packages
          wally-package-types --sourcemap sourcemap.json Packages

      - name: Curl Luau Types
        shell: bash
        run: curl -L "https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/main/scripts/globalTypes.d.lua" > "globalTypes.d.lua"

      - name: Style Code
        run: stylua src

      - name: Generate Sourcemap
        run: rojo sourcemap test.project.json -o sourcemap.json

      - name: Quality Checks
        run: luau-lsp analyze --sourcemap sourcemap.json --definitions globalTypes.d.lua src

      - name: Build
        run: |
          rojo build default.project.json -o roblox-video-codec.rbxm
          rojo build test.project.json -o roblox-video-codec.rbxl

      - name: Deploy Game
        run: rbxcloud experience publish -f roblox-video-codec.rbxl -p ${env:PLACE_ID} -u ${env:GAME_ID} -t published -a 1010 #${env:DEPLOY_API_KEY}

      - name: Login Wally
        run: wally login --token ${env:WALLY_TOKEN}

      - name: Publish Wally
        run: wally publish
