name: Build & Deploy Release

on:
  release:
    types: [published, prerelease]

jobs:
  Get-Release-Version:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.Get-Release-Version.outputs.upload_url }}
      tag_name: ${{ steps.Get-Release-Version.outputs.tag_name }}
    steps:
      - name: Get Release Version
        id: Get-Release-Version
        run: |
          echo "upload_url=${{ github.event.release.upload_url }}" >> $GITHUB_OUTPUT
          echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

  Deploy:
    needs: Get-Release-Version
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wally Packages
        run: wally install

      - name: Generate Sourcemap
        run: rojo sourcemap test.project.json -o sourcemap.json

      - name: Export Wally Package Types
        run: |
          mkdir Packages
          wally-package-types --sourcemap sourcemap.json Packages

      - name: Curl Luau Types
        shell: bash
        run: curl -L "https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/main/scripts/globalTypes.d.lua" > "globalTypes.d.lua"

      - name: Style Code
        run: stylua src

      - name: Generate Sourcemap
        run: rojo sourcemap test.project.json -o sourcemap.json

      - name: Luau LSP Analysis
        run: luau-lsp analyze --sourcemap sourcemap.json --definitions globalTypes.d.lua src

      - name: Update Version Labels
        shell: bash
        run: |
          goal_version_str="${{needs.Get-Release-Version.outputs.tag_name}}"

          wally_toml_contents=$(<wally.toml)

          goal_version_line="version = \"${goal_version_str}\""
          target_version_line=$(echo "$wally_toml_contents" | grep -F "version = ")
          wally_toml_contents="${wally_toml_contents/${target_version_line}/${goal_version_line}}"

          echo "$wally_toml_contents" > "wally.toml"

      - name: Build
        run: |
          rojo build test.project.json -o roblox-video-codec.rbxl
          rojo build default.project.json -o roblox-video-codec.rbxm

      - name: Upload Place Build Artefact
        uses: svenstaro/upload-release-actionv2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: roblox-video-codec.rbxl
          asset_name: Place.rbxm
          tag: ${{ needs.Get-Release-Version.outputs.tag_name }}

      - name: Upload Model Build Artefact
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: roblox-video-codec.rbxm
          asset_name: Model.rbxm
          tag: ${{ needs.Get-Release-Version.outputs.tag_name }}

      - name: Publish Release To Wally
        run: |
          wally login --token "${{secrets.WALLY_TOKEN}}"
          wally publish

      - name: Deploy Release To Roblox
        run: .rbxcloud.exe experience publish --filename roblox-video-codec.rbxl --place-id ${{vars.PLACE_ID}} --universe-id ${{vars.GAME_ID}} --version-type published --api-key ${{secrets.DEPLOY_API_KEY}}
